version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm install hexo-cli -g
      - run: npm install
      - run: hexo generate
      - persist_to_workspace:
          root: ./
          paths:
            - public
  deploy:
    docker:
      - image: dickeyxxx/heroku-cli
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: heroku plugins:install heroku-cli-static
      - run: heroku buildpacks:set -a ebendal-blog https://github.com/hone/heroku-buildpack-static
      - run: heroku static:deploy -a ebendal-blog

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
