version: 2.1
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: npm install hexo-cli -g
      - run: npm install
      - run: hexo generate
      - persist_to_workspace:
          root: ./
          paths:
            - public
  deploy:
    docker:
      - image: governmentpaas/cf-cli
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: cf login -a $PWS_API_URL -u $PWS_USERNAME -p $PWS_PASSWORD -o $PWS_ORG -s $PWS_SPACE
      - run: cf push -d $DOMAIN --hostname $HOSTNAME --route-path $ROUTE_PATH

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
